### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Wertzui123** [CortexPE/Commando#1]
Sorry if this issue is invaled, but what does this plugin? I don't realy checked it.

**Comment by Wertzui123** [comment]
Does this showes command args when you type the command? :thinking:

**Comment by JackMD** [comment]
Maybe you should read the readme

**Comment by Wertzui123** [comment]
I did.

**Comment by Wertzui123** [comment]
But I don't know what it does :joy:

**Comment by CortexPE** [comment]
Read the readme thoroughly please :joy:
