### ISSUE TITLE
Implement arguments for specific permissions

### ISSUE THREAD

**Issue by lukeeey** [CortexPE/Commando#11]
Sometimes we have arguments which require a special permission to be used. This library should add a way to completely omit the arguments from the command if the player does not have permission to use them.

**Comment by CortexPE** [comment]
again, why not just implement it yourself? Adding this would add more complexity and/or unintended behavior to argument parsing because you can have different argument types 

And this already applies to SubCommands

**Comment by lukeeey** [comment]
How would i implement it myself then

**Comment by CortexPE** [comment]
`If` statements

Just check if the argument is set and the player has permissions...

**Comment by lukeeey** [comment]
But i dont want the player to see the arguments they cant access on the client

**Comment by CortexPE** [comment]
Might implement something like `BaseArgument->isVisibleTo(CommandSender
$sender): bool;`

**Comment by CortexPE** [comment]
or just "isUsableBy" because it would affect it anyway

**Comment by rjworks** [comment]
is there a way to do this now
