### ISSUE TITLE
Does not auto-complete with commands containing trailing slashes

### ISSUE THREAD

**Issue by thebigsmileXD** [CortexPE/Commando#14]
Just tried to use the virion in MagicWE2.
After being done, i realized that the client will not receive any suggestions for commands with trailing slashes, i.e. `//set <blocks>`
I am not sure if this a fault in the PacketHooker class, pmmp, or just a client issue, but i can not see any command overloads being sent to the client

**Comment by CortexPE** [comment]
What appears?

Can you send a screenshot?

**Comment by CortexPE** [comment]
This is most likely a client issue

**Comment by thebigsmileXD** [comment]
Closing since this is purely client fault, reported to https://bugs.mojang.com/browse/MCPE-138567 / https://twitter.com/XenialDan/status/1426515221355581442
