### ISSUE TITLE
Parse Order

### ISSUE THREAD

**Issue by CortexPE** [CortexPE/Commando#17]
# The Problem:
There's an issue with the parse order causing undefined and possibly unpredictable behavior

Visualize the following situation:
```py
ArgumentList: [
    [
        RawStringArgument(),
        FloatArgument()
    ]
]
```

What would it return? The `RawStringArgument` which ALWAYS returns true if it's asked if it supports parsing the string?

Or, `FloatArgument`? Which supports decimal & integers only that match a specific regex?

Keep in mind that the parser quits parsing and returns back the result right when it finds a suitable argument class that "can parse" the given string.

This causes issues. A huge issue.

# Proposed Solution:
Make it so that the parsed arguments are returned as arrays uniformly.

If there is only one possible argument for a specific argument position, still return it inside an array.

This will leave the decision making to the developers.

### Backwards-compatibility:
If there is duplicate argument names, do not override the values, rather return an array instead containing all of the parsed values

Minor code changes is needed for existing code.

From (intended behavior: player can be a string or a `Player` object [if online]):
```php
$myPlayer = $args["player"];
```
To:
```php
$myPlayer = $args["player"][0];
```

**Comment by lukeeey** [comment]
Nooo

**Comment by CortexPE** [comment]
Actually, as a second thought I could make it be exactly the same with no BC-breaks

and only return an array if there's already an existing name on the argument list

**Comment by CortexPE** [comment]
Resolved
