### ISSUE TITLE
How do i create a single player selector argument?

### ISSUE THREAD

**Issue by thebigsmileXD** [CortexPE/Commando#19]
How would i create an argument that has a player selector (list of player names online)?

**Comment by CortexPE** [comment]
https://github.com/CortexPE/Hierarchy/blob/master/src/CortexPE/Hierarchy/command/args/MemberArgument.php#L52-L54

**Comment by thebigsmileXD** [comment]
Is there a way to show the item/block icons and item/block names similar to the vanilla `/give` command that you know of? Right now i am sending an enum that contains a list of all items and blocks, but let's face it, that is suboptimal

**Comment by lukeeey** [comment]
I believe you set the enum type to "Item" or "Block" or something like that, idk. I think the client has some predefined enums that you can use.

**Comment by thebigsmileXD** [comment]
Got the answer from discord: Parameter name must be "Item" or "Block", first letter *must* be uppercase

**Comment by lukeeey** [comment]
Yeah its not like anyone already said that..

**Comment by thebigsmileXD** [comment]
@lukeeey I bet you are referring to your answer - there is no enum type Item/Block since json command data was ditched for the new system, thats why i added my answer as "documentation" for people that are looking for a similar issue.
