### ISSUE TITLE
Subcommands show as optional

### ISSUE THREAD

**Issue by thebigsmileXD** [CortexPE/Commando#20]
![grafik](https://user-images.githubusercontent.com/8733998/65211731-0715c300-daa0-11e9-863e-971fd9213bbb.png)
I registered sub commands in a BaseCommand (mye), but the first argument (entity | item), which is the subcommand's name, appears to be optional
When i try to autocomplete the second argument (after entity | item), it shows me all options of the entity and item subcommand
Is there any way to work around this?

**Comment by CortexPE** [comment]
That's intentional because the parent command can still execute under
certain conditions

**Comment by thebigsmileXD** [comment]
Is it still somehow possible to make minecraft complete it when pressing tab? right now i have to type "entity" and "item" manually

**Comment by CortexPE** [comment]
Actually, I think I did some local changes that uses enums to make it 100%
vanilla-like

I'll go look for it and push it

**Comment by lukeeey** [comment]
@CortexPE we discussed this before remember there is a way to get them to show as subcommands. is that what you are talking about?

**Comment by CortexPE** [comment]
Yeah I did the changes on my local files... Not on remote yet

**Comment by thebigsmileXD** [comment]
Many thanks ❤️
