### ISSUE TITLE
PM5

### ISSUE THREAD

**Issue by roimee6** [CortexPE/Commando#43]
Do you think that commando will be updated under pm5

**Comment by thebigsmileXD** [comment]
i hope someone will just PR it as i barely code these days

**Comment by roimee6** [comment]
> i hope someone will just PR it as i barely code these days

I looked at it, I will try to do it myself in the next few days, I don't think there is much to update to PM5

**Comment by roimee6** [comment]
There doesn't seem to be much to change

**Comment by roimee6** [comment]
I've just tested everything and it works like a charm. We're waiting for the final version of PM5 to see if there are any changes
