### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by lukeeey** [CortexPE/Commando#5]
Take a look at the following screenshots. You can clearly see theres too many error messages being fired, when not all of these even apply.

I mean how can i have too many arguments but also have insufficient arguments lol

![image](https://user-images.githubusercontent.com/32024335/58763660-8c0eb800-8555-11e9-8547-0dca92b0e348.png)

![image](https://user-images.githubusercontent.com/32024335/58763658-7dc09c00-8555-11e9-8a69-3572a1b1e00b.png)

**Comment by lukeeey** [comment]
Also the usage is incorrect in console

**Comment by lukeeey** [comment]
Also see that it crashes when no arguments are specified @CortexPE

**Comment by jasonwynn10** [comment]
It must be a fault in your code because I'm not geting the same issues with MyPlot. What did you put in your SessionArgument and RandNameEnumArgument classes?

**Comment by lukeeey** [comment]
its a copy of MemberArgument essentially from cortex's other plugin

![image](https://user-images.githubusercontent.com/32024335/58765018-558d6900-8566-11e9-96fb-269b76b628a0.png)

![image](https://user-images.githubusercontent.com/32024335/58765024-61792b00-8566-11e9-93c7-9f508cced0e6.png)

**Comment by lukeeey** [comment]
No, its not an issue with the enum name because i just changed it and that wouldnt affect the console anyway
@jasonwynn10

**Comment by CortexPE** [comment]
You need to handle the checks for the $args array, you need to check if the
arguments you're looking for are in the array

**Comment by lukeeey** [comment]
@CortexPE Yes but what about the fact that

**Comment by lukeeey** [comment]
@CortexPE Yes but why can you not make it parse arguments in order?

**Comment by lukeeey** [comment]
The main problem here is that, yes, i gave an invalid value for the enum argument, however it is also telling me that i have too many and too little arguments. wtf? thats not possible? I should only get the invalid value error 

![image](https://user-images.githubusercontent.com/32024335/58801704-31cc3080-8603-11e9-9cc7-5025fe2a39a5.png)

**Comment by CortexPE** [comment]
Yeah that is an issue xd
