### ISSUE TITLE
i dont like the way you parse arguments

### ISSUE THREAD

**Issue by lukeeey** [CortexPE/Commando#6]
With the current PMMP system, if you have a command such as `/setrank <player> <rankName>`, if you specify an incorrect player and an incorrect rank, the only error you will get is `Player not found`, as you obviously check that argument first. With this library, it complains about the invalid rank name (its an enum with specific values) and it wont complain about the player not being found until i give a valid rank name.

i dont like this. pls fix

**Comment by CortexPE** [comment]
It wouldn't complain about the player if you didn't check if the player is
online or not in `BaseSubCommand::canParse()`

**Comment by CortexPE** [comment]
And as mentioned on the other issue, you'll need to check the returned
parsed arguments on $args yourself... If it's null or not set
